Extended Commit Message Hook to check every line for length.
Previously only the first line was checked for length.

Review: https://reviews.apache.org/r/45603/

diff --git a/support/hooks/commit-msg b/support/hooks/commit-msg
--- a/support/hooks/commit-msg
+++ b/support/hooks/commit-msg
@@ -10,18 +10,22 @@
 #
 # $ ln -s ../../support/hooks/commit-msg .git/hooks/commit-msg
 
+COMMIT_MESSAGE=$(cat $1)
 FIRST_LINE=$(head -n 1 $1)
 LAST_CHAR=$(echo -n $FIRST_LINE | tail -c 1)
 FIRST_CHAR=$(echo -n $FIRST_LINE | head -c 1)
 
+for LINE in $COMMIT_MESSAGE
+do
+    LENGTH=$(echo $LINE | wc -c)
+    if [ "$LENGTH" -gt "73" ]; then
+        echo >&2 "Error: No line in the commit message summary may exceed 72 characters."
+        exit 1
+    fi
+done
+
 if [[ ! "$FIRST_CHAR" =~ [A-Z] ]]; then
     echo >&2 "Error: Commit message summary (the first line) must start with a capital letter."
-    exit 1
-fi
-
-LENGTH=$(echo $FIRST_LINE | wc -c)
-if [ "$LENGTH" -gt "73" ]; then
-    echo >&2 "Error: Commit message summary (the first line) must not exceed 72 characters."
     exit 1
 fi
 
