Refactored the python bindings into multiple modules.
The existing module has been split into two separate ones:

- mesos.interface - This contains the stub implementations for the
                    Executor/Scheduler as well as the protobufs.
- mesos.native - The old _mesos module.

There is also a base metapackage `mesos` that allows a potential `pip
install mesos` to correctly install everything required. While
mesos.interface can now be uploaded to the cheeseshop, mesos.native
has not changed and will need some more work first.

Review: https://reviews.apache.org/r/23224

diff --git a/src/examples/python/test-executor.in b/src/examples/python/test-executor.in
--- a/src/examples/python/test-executor.in
+++ b/src/examples/python/test-executor.in
@@ -30,12 +30,25 @@ test ! -e ${PROTOBUF_EGG} && \
   echo "${RED}Failed to find ${PROTOBUF_EGG}${NORMAL}" && \
   exit 1
 
-MESOS_EGG=${MESOS_BUILD_DIR}/src/python/dist/
-MESOS_EGG+=mesos-@PACKAGE_VERSION@@PYTHON_EGG_POSTFIX@.egg
+MESOS_EGGS=""
+for egg in interface native; do
+  base_dir="${MESOS_BUILD_DIR}/src/python/${egg}/dist/"
+  egg_path="${base_dir}mesos.${egg}-@PACKAGE_VERSION@"
 
-test ! -e ${MESOS_EGG} && \
-  echo "${RED}Failed to find ${MESOS_EGG}${NORMAL}" && \
-  exit 1
+  if [[ ${egg} == "native" ]]; then
+    egg_path+="@PYTHON_EGG_POSTFIX@"
+  else
+    egg_path+="@PYTHON_EGG_PUREPY_POSTFIX@"
+  fi
+
+  egg_path+=".egg"
+
+  test ! -e ${egg_path} && \
+    echo "${RED}Failed to find ${egg_path}${NORMAL}" && \
+    exit 1
+
+  MESOS_EGGS+="${egg_path}:"
+done
 
 SCRIPT=${MESOS_SOURCE_DIR}/src/examples/python/test_executor.py
 
@@ -43,5 +56,5 @@ test ! -e ${SCRIPT} && \
   echo "${RED}Failed to find ${SCRIPT}${NORMAL}" && \
   exit 1
 
-PYTHONPATH="${DISTRIBUTE_EGG}:${MESOS_EGG}:${PROTOBUF_EGG}" \
+PYTHONPATH="${DISTRIBUTE_EGG}:${PROTOBUF_EGG}:${MESOS_EGGS}" \
   exec ${PYTHON} ${SCRIPT} "${@}"
